
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module gameLogic(

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// GPIO_0, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIOAGPIO,

	//////////// GPIO_1, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIOBGPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

mainStateMachine MainMachine(	.clk(),
											.reset(),
											.setUpDone(),
											.movementLogic(),
											.replay(),
											.delayDone(),
											.setUpGo(),
											.moveGo(),
											.spawnGo(),
											.loseGo(),
											.delayGo()
);
//module mainStateMachine(
//	input wire			clk,
//	input wire			reset,
//	input wire			setUpDone,
//	input wire	[1:0]	movementLogic,
//	input wire 			replay,
//	input wire			delayDone,
//	output wire			setUpGo,
//	output wire			moveGo,
//	output wire 		spawnGo,
//	output wire			loseGo,
//	output wire			delayGo
//);

endmodule
